apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hello-world.fullname" . }}-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host.name }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "hello-world.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
